services:
  postgres:
    image: "postgres:16-alpine"
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "env",
          "pg_isready",
          "--dbname",
          "$$POSTGRES_DB",
          "-U",
          "$$POSTGRES_USER",
        ]
      interval: 10s
      timeout: 10s
      retries: 3
    cpuset: "0-2"
    command: >
      -c max_wal_size=2GB

volumes:
  postgres-data:
